# Generated by Django 4.0.2 on 2022-02-08 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_petphoto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='types',
            new_name='type',
        ),
    ]
