# Generated by Django 4.0.2 on 2022-03-17 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_petphoto_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
